### ISSUE TITLE
Negative Result

### ISSUE THREAD

**Issue by ElahiAli** [AlizadeAlireza/Simple_Counter_solidity#1]
Hi 
I increase the number (increase = 4) and it was ok but 
When i try to decrease the number by 6 , it did not give any answer.why?

**Comment by AlizadeAlireza** [comment]
because I declared my number unsigned integer,
so when user result be nagative it's not work.  
i changed the type of number to int instead using of unsigned integer (uint)  to give us the negative result.
do this solved your problem?

**Comment by ElahiAli** [comment]
thanks @alireza9700
